### ISSUE TITLE
Daterange output in collections is one day off

### ISSUE THREAD

**Issue by gingerchew** [Jako/DaterangeTV#13]
If I enter in a date such as 02/12/2020-02/15/2020 in a collections child, when I view the collections grid (with the column set up with a daterange renderer) the dates appear as 11.-14.February 2020.

So I know:
1. The dates are rendering proper format according to the tv
2. The input is being read by the tv
3. The input is being rendered by the collection grid properly
4. I messed up somewhere (or there is a setting that I'm missing hopefully)

I tried turning on the debugging mode and did not get anything helpful, other than I had the wrong locale value. Fixing that has not fixed my issue.

I'm sure this is something dumb and it's staring me right in the face, but for the life of me I can't figure it out.

I can provide screenshots if that helps, too

**Comment by gingerchew** [comment]
A coworker actually did some more testing and found that if you remove the Daterange custom renderer, the date renders the selected date. I wonder if there is some conflict with a recent update in collections?

**Comment by Jako** [comment]
I have to look for this. Since a renderer is pure javascript, this could be a browser based issue. Maybe something timezone related. But first I have to create a Collection configuration to check the current renderer code.

**Comment by gingerchew** [comment]
Well, here's my browser information:
Google Chrome
Version: 79.0.3945.130 (64-bit)

Timezone: Eastern Standard (EST)

Hopefully this gives some insight! Lemme know if I can help at all 😃

**Comment by Jako** [comment]
I can't reproduce that here with a value set by daterangetv. The tv value is saved like this: `2020-08-06||2020-08-08`. Using your value `02/12/2020-02/15/2020`, the column renders blank in the grid.

The grid column is defined with the following values:
```
name: tv_daterange
renderer: DaterangeTV.Renderer
```

**Comment by gingerchew** [comment]
I believe the 02/12/2020-02/15/2020 was just a shorthand for the date I had entered, not the actual value that was being saved. But it's been so long I could not say for certain. I'm sure I entered in a wrong value in there somewhere. My coworker said she found an alternative, but I can't for the life of me remember which project this was. 

I'm willing to chalk it up to user error at this point haha,

If I do run into this again, it sounds like I should take note of:

- how/what the tv value is saving
- value being entered
- desired value to be shown
- grid column definition

**Comment by Jako** [comment]
The value is read as a string `2020-08-06||2020-08-08` in the renderer, splitted into two parts, transformed into an Date object and formatted with a format string. I don't see any reason, why one of the dates should have an offset of one day.

https://github.com/Jako/DaterangeTV/blob/master/source/js/mgr/daterangetv.renderer.js
