### ISSUE TITLE
year on from and to

### ISSUE THREAD

**Issue by crecorn** [Jako/DaterangeTV#2]
My clients wants the year on both the from and to even if it's in the same year. How would I do this. 

ie.....August 25, 2015 to December 08, 2015

**Comment by Jako** [comment]
You have to write an own snippet for this if you could code PHP. Explode the value and strftime both sub values. 

Other option: Duplicate the current snippet code and remove the 'if' clauses that are suppressing the date parts on equal value (should be all if I am right).

**Comment by Jako** [comment]
Fixed with daterangeTV 1.2.3
