### ISSUE TITLE
Use DateRangePicker to filter GetResources

### ISSUE THREAD

**Issue by carlo-13** [Jako/DaterangeTV#5]
Hi and thanks for your plugin!

Do you think it can be used with DateRangePicker (http://www.daterangepicker.com/#examples) in order to filter GetResources (https://rtfm.modx.com/extras/revo/getresources)?

Thanks for your answer.

Regards,
Carlo.

**Comment by Jako** [comment]
Filtering getResources should be a bit tricky, because of the template variable content format. It is not unixtime and it is a combined value. So you have to filter using a substring.

I have planned to use two template variables containing a start and an end value in a future release.

**Comment by Jako** [comment]
Possible with 1.3.0
