### ISSUE TITLE
after upgrade to 1.3 daterange tv not working

### ISSUE THREAD

**Issue by funkyduke** [Jako/DaterangeTV#6]
After an upgrade to 1.3 (on Modx 2.5.1 or 2.5.2) the TV is not working as it should be, no extra fields are shown in the TV and also the other TV's are influenced. After uninstalling daterange the manager of Modx doesn't start up (white page). Error log: (ERROR @ /data/sites/web/nameofsite/www/core/xpdo/xpdo.class.php : 643) Could not load class: DaterangeTV from daterangetv.
(ERROR @ /data/sites/web/nameofsite/www/core/xpdo/xpdo.class.php : 1259) Problem getting service daterangetv, instance of class DaterangeTV, from path /data/sites/web/nameofsite/www/core/components/daterangetv/model/daterangetv/
I had to manually copy the files from github into the component directory to get back access to the manager.

**Comment by Jako** [comment]
I am not totally sure what went wrong in your installation. Was the whole manager access disturbed? Then for some reason the daterange plugin was not removed, causing this issue. Should not have happened, but it is a MODX uninstall issue. The DaterangeTV installer can't do anything there.

**Comment by funkyduke** [comment]
Let me explain a little more. After the upgrade to 1.3. the TV wasn't working anymore like it should. The TV didn't show the extra fields and even more: all the other TV's had lost their fields also, only the fields 'input option values' and 'default value' are shown. Also every Migx I used with daterange didn't work anymore. So I had to turn back to an older version to fix it.  So I did an uninstall in the package manager of daterange. That worked fine, then I did a remove of the 1.3 package and it was then that I got a white screen. Clearing the cache or reinstalling Modx didn't help. Maybe 1.3. isn't compatible with 2.5.1 or 2.5.2?

**Comment by Jako** [comment]
Checked here. It is compatible. Maybe a browser cache issue with the DaterangeTV javascript.

**Comment by funkyduke** [comment]
OK. let's keep it on a one-time mistake then. For the moment I keep the old version.

**Comment by enminc** [comment]
Just happened to me too. I am on 2.5.0.

I do not have any logged MODX errors but I do have js errors due to bad source links

```
<script src="/assets/components/daterangetv/../../../source/js/mgr/daterangetv.js?v=v1.3.1" type="text/javascript"></script>
<script src="/assets/components/daterangetv/../../../source/js/mgr/daterangetv.templatevar.js?v=v1.3.1" type="text/javascript"></script>
<script src="/assets/components/daterangetv/../../../source/js/mgr/daterangetv.renderer.js?v=v1.3.1" type="text/javascript"></script>
```

These are internal dev links that are being setup in the class due to a typo ... I believe.

Line 142
```
if ($this->getOption('debug') && $this->getOption('assetsUrl') != MODX_ASSETS_URL . 'components/daterangetv/' || true) {
```

|| true is always going to send us down this rabbit hole :)

I remove "|| true" and UI comes back to life.

**Comment by Jako** [comment]
O.k. Then the issue is clear. My fault. Sorry for this.

**Comment by Jako** [comment]
New Release 1.3.1-pl2 is available via package management.
