### ISSUE TITLE
still broken

### ISSUE THREAD

**Issue by funkyduke** [Jako/DaterangeTV#8]
DaterangeTV is still broken after update from 1.2.3.

In combination with Migx the daterangeTV breaks down the Migx. You can't give in a date and the other fields are corrupt.

**Comment by Jako** [comment]
Are there any errors in the browser console?

**Comment by funkyduke** [comment]
Nothing in the log. Best way to test it is to make a TV with daterange and bind this to a Migx. You will see it's broken.

**Comment by Jako** [comment]
Working fine here in MIGX with the latest DaterangeTV 1.3.2 and the following test configuration, but 1.3.0 should have no issues either:

```
{
  "formtabs": [
    {
      "MIGX_id": 1,
      "caption": "DaterangeTV",
      "fields": [
        {
          "MIGX_id": 1,
          "field": "daterange",
          "caption": "Daterange",
          "inputTVtype": "daterange"
        }
      ]
    }
  ],
  "columns": [
    {
      "MIGX_id": 1,
      "header": "Daterange",
      "dataIndex": "daterange",
      "show_in_grid": 1,
      "customrenderer": "DaterangeTV.Renderer",
      "renderer": "DaterangeTV.Renderer"
    }
  ]
}
```
